---
- name: Ensure config directory exists
  ansible.builtin.file:
    path: /etc/simple_django
    state: directory
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "u=rwx,g=rwx,o=rx"

- name: Ensure app user is setup
  block:
    - name: Ensure app group exists
      ansible.builtin.group:
        name: simple_django
        system: true
        gid: 700
        state: present

    - name: Ensure app user exists
      ansible.builtin.user:
        name: simple_django
        system: true
        group: simple_django
        uid: 700
        create_home: false

- name: Ensure data directory is present
  ansible.builtin.file:
    path: /var/simple_django
    owner: simple_django
    group: simple_django
    state: directory
    mode: "u=rwx,g=rwx,o="

- name: Template out litestream config
  ansible.builtin.template:
    src: litestream.yml.j2
    dest: /etc/clarohq/litestream.yml
    owner: clarohq
    group: clarohq
    mode: "u=r,g=r,o=r"

- name: Copy db restore script
  ansible.builtin.copy:
    src: restore-db.sh
    dest: /root/restore-db.sh
    mode: "u=rx,g=,o="
